stages:
  - test
  - build
  - deploy-staging
  - deploy-production

# -------------------------- Test -------------------------- #
Test:
  stage: test
  image: maven:latest
  tags:
    - dalfcs_docker_autoscale
  script:
    - cd server
    - mvn clean verify
  artifacts:
    when: always
    reports:
      junit:
        - server/target/surefire-reports/TEST-*.xml
        - server/target/failsafe-reports/TEST-*.xml
    
# -------------------------- Build Server for Dev -------------------------- #
Build Server for Dev:
  stage: build
  image: maven:latest
  tags:
    - dalfcs_docker_autoscale
  script:
    - cd server
    - mvn clean package -DskipTests=true
  artifacts:
    paths:
       - server/target/*.jar
  except:
    - main
    - tag

# -------------------------- Build Server for Staging -------------------------- #
Build Server for Staging:
  stage: build
  image: maven:latest
  tags:
    - dalfcs_docker_autoscale
  script:
    - cd server
    - mvn clean package -DskipTests=true -Pstaging
  artifacts:
    paths:
       - server/target/*.jar
  only:
    - main

# -------------------------- Build Server for Production -------------------------- #
Build Server for Prod:
  stage: build
  image: maven:latest
  tags:
    - dalfcs_docker_autoscale
  script:
    - cd server
    - mvn clean package -DskipTests=true -Pprod
  artifacts:
    paths:
       - server/target/*.jar
  only:
    - tag

# -------------------------- Build Client -------------------------- #
Build Client:
  stage: build
  image: node:16
  tags:
    - dalfcs_docker_autoscale
  script:
    - cd client
    - npm install
    - npm run build

# -------------------------- Deploy on Staging -------------------------- #
Deploy Staging Client:
  stage: deploy-staging
  image: ruby:latest
  tags:
    - dalfcs_docker_autoscale  
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
  script:
    - cd client
    - dpl --provider=heroku --app=$STAGING_CLIENT_HEROKU_APP_NAME --api-key=$HARSH_HEROKU_API_KEY --cleanup
  only:
    - main

Deploy Staging Server:
  stage: deploy-staging
  image: ruby:latest
  tags:
    - dalfcs_docker_autoscale  
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
  script:
    - > 
      curl --request PATCH "https://api.heroku.com/apps/$STAGING_SERVER_HEROKU_APP_NAME/config-vars"  
      --data "{\"SPRING_PROFILES_ACTIVE\": \"staging\"}" 
      --header "Content-Type: application/json" 
      --header "Accept: application/vnd.heroku+json; version=3" 
      --header "Authorization: Bearer $HARSH_HEROKU_API_KEY"
    - cd server
    - dpl --provider=heroku --app=$STAGING_SERVER_HEROKU_APP_NAME --api-key=$HARSH_HEROKU_API_KEY --cleanup
  only:
    - main

# -------------------------- Deploy on Prod -------------------------- #
Deploy Production Client:
  stage: deploy-production
  image: ruby:latest
  tags:
    - dalfcs_docker_autoscale  
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
  script:
    - cd client
    - dpl --provider=heroku --app=$PRODUCTION_CLIENT_HEROKU_APP_NAME --api-key=$HARSH_HEROKU_API_KEY --cleanup
  only:
    - tag

Deploy Production Server:
  stage: deploy-production
  image: ruby:latest
  tags:
    - dalfcs_docker_autoscale  
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
  script:
    - > 
      curl --request PATCH "https://api.heroku.com/apps/$PRODUCTION_SERVER_HEROKU_APP_NAME/config-vars"  
      --data "{\"SPRING_PROFILES_ACTIVE\": \"prod\"}" 
      --header "Content-Type: application/json" 
      --header "Accept: application/vnd.heroku+json; version=3" 
      --header "Authorization: Bearer $HARSH_HEROKU_API_KEY"
    - cd server
    - dpl --provider=heroku --app=$PRODUCTION_SERVER_HEROKU_APP_NAME --api-key=$HARSH_HEROKU_API_KEY --cleanup
  only:
    - tag
